# Generated by Django 4.2.30 on 2026-04-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atendimentos', 'Atendimentos'), ('taxa_ocupacao', 'Taxa de Ocupação (%)'), ('eventos_adversos', 'Eventos Adversos'), ('ocorrencias', 'Ocorrências'), ('tempo_resposta', 'Tempo de Resposta (min)'), ('qualidade', 'Indicador de Qualidade (%)'), ('obitos', 'Óbitos'), ('infeccoes', 'Infecções Hospitalares'), ('prescricoes', 'Prescrições'), ('exames', 'Exames Realizados'), ('plantoes', 'Plantões'), ('outro', 'Outro')], max_length=30)),
                ('nome_custom', models.CharField(blank=True, help_text='Nome personalizado (opcional)', max_length=100)),
                ('limite_atencao', models.FloatField(blank=True, help_text='Valor a partir do qual gera alerta de atenção', null=True)),
                ('limite_critico', models.FloatField(blank=True, help_text='Valor a partir do qual gera alerta crítico', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['setor', 'tipo'],
                'unique_together': {('setor', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_referencia', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='normal', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='indicadores.indicador')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-data_referencia', '-criado_em'],
            },
        ),
    ]
