# Generated by Django 4.2.30 on 2026-04-14 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoNSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('queda', 'Queda de Paciente'), ('lpp', 'Lesão por Pressão (LPP)'), ('erro_medicacao', 'Erro de Medicação'), ('identificacao', 'Falha na Identificação do Paciente'), ('cirurgia', 'Cirurgia em Local Errado'), ('transfusao', 'Reação Transfusional'), ('infeccao', 'Infecção Associada à Assistência'), ('comunicacao', 'Falha de Comunicação'), ('outro', 'Outro')], max_length=20)),
                ('meta_relacionada', models.CharField(blank=True, choices=[('meta_1', 'Meta 1 — Identificação correta do paciente'), ('meta_2', 'Meta 2 — Comunicação efetiva entre profissionais'), ('meta_3', 'Meta 3 — Segurança de medicamentos de alta vigilância'), ('meta_4', 'Meta 4 — Cirurgia segura (local correto)'), ('meta_5', 'Meta 5 — Higiene das mãos / prevenção de infecções'), ('meta_6', 'Meta 6 — Prevenção de quedas e lesões')], help_text='Preenchido automaticamente com base no tipo', max_length=10)),
                ('data_ocorrencia', models.DateField()),
                ('hora_ocorrencia', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('dano', models.CharField(choices=[('nenhum', 'Sem Dano'), ('leve', 'Dano Leve'), ('moderado', 'Dano Moderado'), ('grave', 'Dano Grave'), ('obito', 'Óbito')], default='nenhum', max_length=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída'), ('arquivada', 'Arquivada')], default='aberta', max_length=15)),
                ('plano_acao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('notificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_nsp', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Notificação NSP',
                'verbose_name_plural': 'Notificações NSP',
                'ordering': ['-data_ocorrencia', '-criado_em'],
            },
        ),
    ]
