# Generated by Django 4.2.30 on 2026-04-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicadores', '0001_initial'),
        ('setores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='info', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_lidos', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='indicadores.registro')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
