# Generated by Django 4.2.30 on 2026-04-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('direcao', 'Direção'), ('diretoria', 'Diretoria'), ('gerencia', 'Gerência'), ('assistencial', 'Assistencial'), ('administrativo', 'Administrativo'), ('unidade', 'Unidade'), ('comissao', 'Comissão')], max_length=20)),
                ('nivel', models.IntegerField(default=0)),
                ('cor', models.CharField(default='#185FA5', max_length=10)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nivel', 'nome'],
            },
        ),
    ]
