# Generated by Django 4.2.30 on 2026-04-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0002_alter_setor_tipo_add_nucleo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoFisio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=200)),
                ('prontuario', models.CharField(blank=True, max_length=50)),
                ('modalidade', models.CharField(choices=[('internado', 'Paciente Internado'), ('uti', 'UTI'), ('ambulatorial', 'Ambulatorial'), ('domiciliar', 'Domiciliar')], default='internado', max_length=15)),
                ('especialidade', models.CharField(choices=[('respiratoria', 'Fisioterapia Respiratória'), ('ortopedica', 'Fisioterapia Ortopédica'), ('neurologica', 'Fisioterapia Neurológica'), ('cardiovascular', 'Fisioterapia Cardiovascular'), ('pediatrica', 'Fisioterapia Pediátrica'), ('outro', 'Outro')], default='respiratoria', max_length=15)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('realizado', 'Realizado'), ('falta', 'Falta'), ('cancelado', 'Cancelado')], default='agendado', max_length=15)),
                ('data_atendimento', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('numero_sessao', models.PositiveSmallIntegerField(default=1, verbose_name='N° da Sessão')),
                ('descricao_clinica', models.TextField(blank=True, help_text='Resumo clínico / diagnóstico')),
                ('objetivos', models.TextField(blank=True, help_text='Objetivos terapêuticos')),
                ('evolucao', models.TextField(blank=True, help_text='Evolução da sessão')),
                ('alta_fisioterapeutica', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_fisio', to=settings.AUTH_USER_MODEL)),
                ('setor_origem', models.ForeignKey(help_text='Setor/ala de origem do paciente', on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_fisio', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Atendimento de Fisioterapia',
                'verbose_name_plural': 'Atendimentos de Fisioterapia',
                'ordering': ['-data_atendimento', '-criado_em'],
            },
        ),
    ]
